### ISSUE TITLE
Could not find or load assembly Microsoft.WindowsAPICodePack.Shell

### ISSUE THREAD

**Issue by kevingy** [UziTech/NSF2SQL#10]
I'm getting this error after clicking Search Server:

![image](https://user-images.githubusercontent.com/411556/61809470-f976f080-ae02-11e9-8f78-df84cfe6784b.png)

I've attempted to download the Microsoft.WindowsAPICodePack.Shell.dll from Nuget. I've placed it in the directory with the application, but it didn't seem to help. I also installed nuget.exe and installed it using Nuget. Neither worked. Do you have any suggestions?

**Comment by UziTech** [comment]
Did you download the application from the latest release zip file [NSF2SQL.zip](https://github.com/UziTech/NSF2SQL/releases/tag/v0.1.1)?

That dll should be included in the zip file

![image](https://user-images.githubusercontent.com/97994/61810825-b8341000-ae05-11e9-9eb0-10a66af4895d.png)

**Comment by kevingy** [comment]
I must not have. After downloading that file, it's working great. Thank you!
