### ISSUE TITLE
Executing the app

### ISSUE THREAD

**Issue by andreasinspire** [UziTech/NSF2SQL#12]
Downloaded and executed the app to get the error below
![image](https://user-images.githubusercontent.com/34400269/71313862-cd11df80-2447-11ea-99d4-efcc53924f16.png)
Any support will be greatly appreciated

**Comment by UziTech** [comment]
Do you have lotus notes installed on the computer you are trying to run this on?

**Comment by andreasinspire** [comment]
Thank you for the response. No I do not. I was given only access to the NSF. Cant we run this without LN being installed?

**Comment by UziTech** [comment]
Yes this software uses a dll from lotus notes. It depends on the dll for the version of lotus notes that created the nsf file.

**Comment by andreasinspire** [comment]
Ok. Thank you again. We will obtain LN and deploy. Will get back here if needed

**Comment by andreasinspire** [comment]
Dear Tony

Hope all is well

We parked this for a while due to other priorities and now we restarted it

We now have a server and deployed the app on it. .net framework deployed and also MySQL

 

A naïve question

When selecting Search Server we enter the server name that hosts the Lotus notes (it is the same server that we run the app on)

What is not clear is the domain and the password. They refer to which user? The currently logged on one? I.e the app uses the currently logon user and needs the domain and password?

**Comment by UziTech** [comment]
Yes the domain and password for the currently logged in user.

**Comment by andreasinspire** [comment]
Excellent and I APPRECIATE the quick response

**Comment by andreasinspire** [comment]
Dear Tony

We did run a first migration that went very well. Data has been extracted into an SQL load file that we loaded into MySQL

We have a question on files we got the below table with a reference (we assume) of a file. Yet where is the actual file located?

 



 

From: andreas.theodosiou@inspireobjects.com <andreas.theodosiou@inspireobjects.com> 
Sent: Wednesday, 6 January 2021 7:13 PM
To: 'UziTech/NSF2SQL' <reply@reply.github.com>; 'UziTech/NSF2SQL' <NSF2SQL@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [UziTech/NSF2SQL] Executing the app (#12)

 

Excellent and I APPRECIATE the quick response

**Comment by andreasinspire** [comment]
Dear Tony good day
As  kind reminder on the below

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: andreas.theodosiou@inspireobjects.com <andreas.theodosiou@inspireobjects.com>
Sent: Wednesday, January 13, 2021 8:46:48 PM
To: 'UziTech/NSF2SQL' <reply@reply.github.com>; 'UziTech/NSF2SQL' <NSF2SQL@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [UziTech/NSF2SQL] Executing the app (#12)


Dear Tony

We did run a first migration that went very well. Data has been extracted into an SQL load file that we loaded into MySQL

We have a question on files we got the below table with a reference (we assume) of a file. Yet where is the actual file located?



[cid:image002.png@01D6E9ED.360645B0]



From: andreas.theodosiou@inspireobjects.com <andreas.theodosiou@inspireobjects.com>
Sent: Wednesday, 6 January 2021 7:13 PM
To: 'UziTech/NSF2SQL' <reply@reply.github.com>; 'UziTech/NSF2SQL' <NSF2SQL@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [UziTech/NSF2SQL] Executing the app (#12)



Excellent and I APPRECIATE the quick response

**Comment by andreasinspire** [comment]
Dear Tony

A kind reminder on the below issue

Also we run the migration on a large NSF (15GB) and we get the below at the end of the processing but before exporting the files. Can we see why?



 

From: andreas.theodosiou@inspireobjects.com <andreas.theodosiou@inspireobjects.com> 
Sent: Wednesday, 13 January 2021 8:47 PM
To: 'UziTech/NSF2SQL' <reply@reply.github.com>; 'UziTech/NSF2SQL' <NSF2SQL@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [UziTech/NSF2SQL] Executing the app (#12)

 

Dear Tony

We did run a first migration that went very well. Data has been extracted into an SQL load file that we loaded into MySQL

We have a question on files we got the below table with a reference (we assume) of a file. Yet where is the actual file located?

 



 

From: andreas.theodosiou@inspireobjects.com <mailto:andreas.theodosiou@inspireobjects.com>  <andreas.theodosiou@inspireobjects.com <mailto:andreas.theodosiou@inspireobjects.com> > 
Sent: Wednesday, 6 January 2021 7:13 PM
To: 'UziTech/NSF2SQL' <reply@reply.github.com <mailto:reply@reply.github.com> >; 'UziTech/NSF2SQL' <NSF2SQL@noreply.github.com <mailto:NSF2SQL@noreply.github.com> >
Cc: 'Author' <author@noreply.github.com <mailto:author@noreply.github.com> >
Subject: RE: [UziTech/NSF2SQL] Executing the app (#12)

 

Excellent and I APPRECIATE the quick response

**Comment by UziTech** [comment]
> where is the actual file located?

It should be on the desktop in a file called `export.sql`

> Also we run the migration on a large NSF (15GB) and we get the below at the end of the processing but before exporting the files. Can we see why?

what is "the below" there doesn't seem to be any other information below that.

**Comment by andreasinspire** [comment]
The SQL file not created. When we run it on a smaller DB it runs ok (no exception) and the file is created.

When referring to the below, I meant my below email. I add again here

 

Dear Tony

We did run a first migration that went very well. Data has been extracted into an SQL load file that we loaded into MySQL

We have a question: on files we got the below table with a reference (we assume) of a file. Yet where is the actual file located?

**Comment by UziTech** [comment]
You might be running into https://github.com/UziTech/NSF2SQL/issues/1. The software loads all documents into memory so it knows how to arrange the tables before outputting the SQL. I haven't found an easy way to reduce the memory footprint.

I think the easiest way around this is to break the NSF database into multiple databases and merge them when they are in sql.

**Comment by andreasinspire** [comment]
Thank you

How about the documents/attachments

Where are they located? Is export of documents (attachments in NSF) supported?

**Comment by UziTech** [comment]
I don't believe it does anything with attachments. We didn't have any in the databases I needed to convert when I created this.

**Comment by andreasinspire** [comment]
Than you Tony
