### ISSUE TITLE
the apps ask password for opening file

### ISSUE THREAD

**Issue by SniperRus** [UziTech/NSF2SQL#13]
when i try to open nsf file it ask for password? what password should I use?
do i need copy my id file to app's directory?

and what syntax for server connection?
name of the phisical-server? 
domain.. ok, but password again.. without username?

**Comment by UziTech** [comment]
Should be the your password for lotus notes.

Could you add a screenshot so I can see which dialog box is asking for a password?

**Comment by Marc7Wunder** [comment]
![image](https://user-images.githubusercontent.com/15094554/72513555-708ac000-384d-11ea-8bc0-20c6f56e0dcc.png)

this is what it looks like for me. Just for your information.

**Comment by UziTech** [comment]
The application needs your Lotus Notes password to connect to the domino database.

**Comment by UziTech** [comment]
If this is still an issue feel free to re-open it.
