### ISSUE TITLE
Are attachments handled

### ISSUE THREAD

**Issue by summne01** [UziTech/NSF2SQL#35]
I'm going to try this when my IT dept have renewed my Domino certificate. Quick question... One of our Lotus Notes R5 databases I want to migrate has PDF attachments with each record. Does your tool handle the attachments and dump them to a folder which can be references by the outputted tables? Cheers.

**Comment by UziTech** [comment]
This does not do anything with the attachments.

**Comment by andreamorello93** [comment]
I would also appreciate this feature! fantastic project @UziTech, do you think this will be implement?

**Comment by UziTech** [comment]
If someone wants to create a PR for this feature I would be willing to merge it but I don't have a domino server to test this on any more.

**Comment by andreamorello93** [comment]
@UziTech @summne01 this is the code that i've just tested and
 works well form me

`
                        foreach (NotesItem nItem in items)
                        {

                            if (nItem.Name == "$FILE")
                            {
                                NotesItem file = doc.GetFirstItem("$File");

                                string fileName = ((object[])nItem.Values)[0].ToString();

                                NotesEmbeddedObject attachfile = (NotesEmbeddedObject)doc.GetAttachment(fileName);

                                if (attachfile != null)
                                {
                                    attachfile.ExtractFile("C:\\test\\" + fileName);
                                }
                            }
                        }`

Write this during documents cicle and is done

...But all the credits goes to @UziTech for this fantastic little and useful software! ty very much!

**Comment by Ihkusala** [comment]
Is @andreamorello93 code implement to newest version? If not could someone help me out how to add that by myself?

**Comment by UziTech** [comment]
The code is not implemented.

**Comment by namle-dev** [comment]
@andreamorello93 can you please create that PR? thank you so much!

**Comment by andreamorello93** [comment]
Of course I'll do that

**Comment by andreamorello93** [comment]
#71

**Comment by namle-dev** [comment]
> #71

Thanks bro!

**Comment by andreamorello93** [comment]
> > #71
> 
> Thanks bro!

LMK

**Comment by UziTech** [comment]
released as [v0.3.0](https://github.com/UziTech/NSF2SQL/releases/tag/v0.3.0)
