### ISSUE TITLE
"Object reference not set to an instance of the object" error

### ISSUE THREAD

**Issue by mwbonett** [UziTech/NSF2SQL#7]
Hello,
I am trying to open a Notes 9.x .nsf database with this tool. After entering the Notes password I get a popup with the text "Object reference not set to an instance of the object", and cannot proceed further with the target database. What can I do to better diagnose this issue? Thanks!

**Comment by UziTech** [comment]
you could try installing [Visual Studio Community 2017](https://visualstudio.microsoft.com/downloads/), cloning this repo and debugging it.

I tried a few things but wasn't able to reproduce it. Although it could be because I only have Lotus Notes 8.5
