### ISSUE TITLE
Grateful for a new release

### ISSUE THREAD

**Issue by jack80342** [UziTech/NSF2SQL#73]
Thanks for this awesome project.
Could you please publish a new release?
Tried many days to build a .exe file,but failed.

**Comment by UziTech** [comment]
Unfortunately I don't have access to a domino server any more, which I think is a requirement. Last time I tried I couldn't get it to work, but I will try tonight.

**Comment by UziTech** [comment]
I was able to get a release out [v0.3.0](https://github.com/UziTech/NSF2SQL/releases/tag/v0.3.0)
